### ISSUE TITLE
Add an option to return the response for non 200 okay

### ISSUE THREAD

**Issue by ADKebert** [rocketjob/opinionated_http#3]
### Environment

Provide at least:
* Ruby Version. 2.3.7
* Persistent HTTP Version. 2.0.3
* Semantic Logger Version. 4.6.1
* Secret Config Version. 0.7.0
* Opinionated HTTP Version.
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.). Rails 5.2.4.1

### Expected Behavior

Have an endpoint which returns 400 responses that include a body with additional information.  Want to access this information and decide whether to raise an error or not outside of opinionated_http

### Actual Behavior

Opinionated http raises an error with the "bad response" message but there's no way to get to the additional information

### Pull Request

* Consider submitting a Pull Request with a fix for the issue.
* Or, even a Pull request that only includes a test that reproduces the problem.

**Comment by reidmorrison** [comment]
Added
